### ISSUE TITLE
VS error

### ISSUE THREAD

**Issue by FranklinOP-IND** [StrafeTool/waloranti#1]
![image](https://user-images.githubusercontent.com/64591314/195023708-6bcd14cd-0baf-4a0f-a22d-36f5f64dd7d0.png)
i set path sdk but idk why error show me

**Comment by ericshug** [comment]
same too

**Comment by FranklinOP-IND** [comment]
> ![image](https://user-images.githubusercontent.com/64591314/195023708-6bcd14cd-0baf-4a0f-a22d-36f5f64dd7d0.png) i set path sdk but idk why error show me

Update render_menu.hpp
#include <dxsdk-d3dx/D3DX11.h> To #include <d3dx11.h>

NEW ISSUE 
https://prnt.sc/Iks9APflHQJC

**Comment by uhhdexz** [comment]
Im also having the new issue have you found a fix for that?
